# -*- coding: utf-8 -*-
"""FinalAutoResearcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGREfapMjPoMB3wVg2_95brPFa7ii85u
"""

!pip install -q langchain google-generativeai langchain-google-genai
!apt-get install -y pandoc
!pip install pypandoc

import google.generativeai as genai

API_KEY = "my api key"
genai.configure(api_key=API_KEY)


# LOADING GEMINI MODEL
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-flash-latest",
    temperature=0.7,
    google_api_key=API_KEY
)


# SAFE API CALL
import time

def safe_invoke(prompt):
    for i in range(1):
        try:
            response = llm.invoke(prompt)
            content = response.content

            if isinstance(content, list):
                return "".join([part.get('text', '') for part in content if isinstance(part, dict)])
            else:
                return content
        except Exception as e:
            print(f"⚠️ Retry {i+1} due to error: {e}")
            time.sleep(10)
    return "Error: API limit reached"


# AGENTS
# PLANNING AGENT
def planner_agent(topic):
    prompt = f"""
    You are a planner agent.

    Break the topic into clear structured sections.

    Topic: {topic}

    Output only section headings in bullet format.
    """
    return safe_invoke(prompt)


# RESEARCHING AGENT
def research_agent(topic):
    prompt = f"""
    You are a research agent.

    Provide detailed research points on:
    {topic}

    Include facts, examples, and explanations.
    """
    return safe_invoke(prompt)


# WRITING AGENT
def writer_agent_full(plan, research):
    prompt = f"""
    You are a writer agent.

    Write a complete structured report using:

    Sections:
    {plan}

    Research:
    {research}

    Make it detailed, well-structured, and readable.
    """
    return safe_invoke(prompt)


# EDITING AGENT
def editor_agent(content):
    prompt = f"""
    You are an editor.

    Improve the following content:
    - Fix grammar
    - Improve flow
    - Remove repetition

    Content:
    {content}
    """
    return safe_invoke(prompt)


# PRESENTING AGENT
def presentation_agent(content):
    prompt = f"""
    Create:
    1. Executive Summary
    2. Slide Outline (bullet points)

    Content:
    {content}
    """
    return safe_invoke(prompt)


# MAIN PIPELINE
def auto_researcher(topic):

    print("Planning...")
    plan = planner_agent(topic)
    time.sleep(1)
    print("Planning Done.")

    print("Researching...")
    research = research_agent(topic)
    time.sleep(1)
    print("Researching Done.")

    print("Writing Full Report...")
    report = writer_agent_full(plan, research)
    time.sleep(1)
    print("Writing Report Done.")

    print("Editing...")
    edited = editor_agent(report)
    time.sleep(1)
    print("Editing Done.")

    print("Creating Presentation...")
    presentation = presentation_agent(edited)
    print("Presentation Created.")

    # Construct the final markdown output here
    final_markdown_content = f"""
# AUTORESEARCH REPORT

## TOPIC
{topic}
----
## FULL REPORT
{edited}
----
## EXECUTIVE SUMMARY AND PRESENTATION
{presentation}
"""
    return final_markdown_content # Explicitly return the markdown string

# RUNNING THE PROJECT
topic = input("Enter the topic for the report: ")

final_output = auto_researcher(topic)

print(final_output)


# SAVE MARKDOWN FILE
with open("AutoResearch_Report.md", "w", encoding="utf-8") as f:
    f.write(final_output)

print("Markdown file saved!")


# DOWNLOAD MARKDOWN FILE
from google.colab import files
files.download("AutoResearch_Report.md")